
[[redirects]]
  from = "/voca-api/*"
  to = "http://61.102.114.235:17080/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/kakao/*"
  to = "https://kauth.kakao.com/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200